import type { Locale } from "@/lib/i18n";

type PageCopy = { navigation:string; fragmentsLink:string; privacy:string; languageLabel:string; comingSoon:string; promise:string; discover:string; heroNote:string; foundLabel:string; foundTitle:string; foundIntro:string; fragment:string; moreSoon:string; privateTitle:string; privateBody:string; footerLine:string; play:string; pause:string; timeline:string };
type FragmentCopy = { title:string; text:string[]; alt:string };

export const comingSoonCopy: Record<Locale, PageCopy> = {
  en:{navigation:"Pre-launch navigation",fragmentsLink:"Found fragments",privacy:"Privacy",languageLabel:"Language",comingSoon:"Coming soon.",promise:"No cloud. No feed. No noise.",discover:"Find the first fragments",heroNote:"We lost the road. The afternoon found us instead.",foundLabel:"A little preview of NoFi",foundTitle:"Found fragments",foundIntro:"Three real memories. A photograph, a few words, sometimes a voice. Nothing made for an audience.",fragment:"Fragment",moreSoon:"Another fragment soon.",privateTitle:"Private by design. Offline by choice.",privateBody:"No account. No public feed. Your diary stays close, even in airplane mode.",footerLine:"Made to be kept.",play:"Play this memory",pause:"Pause this memory",timeline:"Memory audio timeline"},
  it:{navigation:"Navigazione pre-lancio",fragmentsLink:"Frammenti ritrovati",privacy:"Privacy",languageLabel:"Lingua",comingSoon:"Presto.",promise:"Niente cloud. Niente feed. Niente rumore.",discover:"Scopri i primi frammenti",heroNote:"Abbiamo perso la strada. Il pomeriggio, invece, ha trovato noi.",foundLabel:"Una piccola anteprima di NoFi",foundTitle:"Frammenti ritrovati",foundIntro:"Tre ricordi reali. Una fotografia, poche parole, a volte una voce. Niente che sia stato creato per un pubblico.",fragment:"Frammento",moreSoon:"Un altro frammento, presto.",privateTitle:"Privato per design. Offline per scelta.",privateBody:"Nessun account. Nessun feed pubblico. Il tuo diario resta vicino, anche in modalità aereo.",footerLine:"Fatto per essere custodito.",play:"Ascolta questo ricordo",pause:"Metti in pausa questo ricordo",timeline:"Linea temporale dell’audio del ricordo"},
  fr:{navigation:"Navigation avant lancement",fragmentsLink:"Fragments retrouvés",privacy:"Confidentialité",languageLabel:"Langue",comingSoon:"Bientôt.",promise:"Pas de cloud. Pas de fil. Pas de bruit.",discover:"Découvrir les premiers fragments",heroNote:"Nous avons perdu la route. L’après-midi, lui, nous a trouvés.",foundLabel:"Un petit aperçu de NoFi",foundTitle:"Fragments retrouvés",foundIntro:"Trois vrais souvenirs. Une photographie, quelques mots, parfois une voix. Rien qui ait été créé pour un public.",fragment:"Fragment",moreSoon:"Un autre fragment, bientôt.",privateTitle:"Privé par conception. Hors ligne par choix.",privateBody:"Aucun compte. Aucun fil public. Votre journal reste près de vous, même en mode avion.",footerLine:"Fait pour être gardé.",play:"Écouter ce souvenir",pause:"Mettre ce souvenir en pause",timeline:"Progression audio du souvenir"},
  es:{navigation:"Navegación de prelanzamiento",fragmentsLink:"Fragmentos encontrados",privacy:"Privacidad",languageLabel:"Idioma",comingSoon:"Muy pronto.",promise:"Sin nube. Sin feed. Sin ruido.",discover:"Descubre los primeros fragmentos",heroNote:"Perdimos el camino. La tarde, en cambio, nos encontró.",foundLabel:"Un pequeño adelanto de NoFi",foundTitle:"Fragmentos encontrados",foundIntro:"Tres recuerdos reales. Una fotografía, unas palabras, a veces una voz. Nada creado para un público.",fragment:"Fragmento",moreSoon:"Otro fragmento, muy pronto.",privateTitle:"Privado por diseño. Sin conexión por elección.",privateBody:"Sin cuenta. Sin feed público. Tu diario permanece cerca, incluso en modo avión.",footerLine:"Hecho para conservarse.",play:"Escuchar este recuerdo",pause:"Pausar este recuerdo",timeline:"Progreso del audio del recuerdo"},
  de:{navigation:"Pre-Launch-Navigation",fragmentsLink:"Gefundene Fragmente",privacy:"Datenschutz",languageLabel:"Sprache",comingSoon:"Demnächst.",promise:"Keine Cloud. Kein Feed. Kein Lärm.",discover:"Die ersten Fragmente entdecken",heroNote:"Wir verloren den Weg. Der Nachmittag fand dafür uns.",foundLabel:"Ein kleiner Vorgeschmack auf NoFi",foundTitle:"Gefundene Fragmente",foundIntro:"Drei echte Erinnerungen. Ein Foto, ein paar Worte, manchmal eine Stimme. Nichts davon war für ein Publikum bestimmt.",fragment:"Fragment",moreSoon:"Bald ein weiteres Fragment.",privateTitle:"Privat konzipiert. Offline aus Überzeugung.",privateBody:"Kein Konto. Kein öffentlicher Feed. Dein Tagebuch bleibt bei dir, selbst im Flugmodus.",footerLine:"Gemacht, um bewahrt zu werden.",play:"Diese Erinnerung anhören",pause:"Diese Erinnerung pausieren",timeline:"Audiofortschritt der Erinnerung"},
};

export const fragments: Array<{ id:string; slug:string; image:string; audio?:string; duration?:number; copy:Record<Locale,FragmentCopy> }> = [
  {id:"001",slug:"fuori_strada",image:"/memories/screens/fuori-strada-full.jpeg",audio:"/memories/audio/fuori-strada.m4a",duration:23,copy:{
    en:{title:"Somewhere on the way to the sea",text:["We took the wrong turn and found a wall warmed by the sun.","Music drifted from a bar nearby. For a while, nobody wanted the right road back."],alt:"A sunlit travel memory made in NoFi"},
    it:{title:"Da qualche parte, andando verso il mare",text:["Abbiamo sbagliato strada e trovato un muro scaldato dal sole.","Da un bar arrivava della musica. Per un po’, nessuno ha voluto ritrovare la via giusta."],alt:"Un ricordo di viaggio assolato creato con NoFi"},
    fr:{title:"Quelque part sur la route de la mer",text:["Nous avons pris le mauvais chemin et trouvé un mur chauffé par le soleil.","La musique d’un bar voisin arrivait jusqu’à nous. Pendant un moment, personne n’a voulu retrouver la bonne route."],alt:"Un souvenir de voyage ensoleillé créé dans NoFi"},
    es:{title:"En algún lugar camino al mar",text:["Tomamos el camino equivocado y encontramos un muro calentado por el sol.","Desde un bar cercano llegaba música. Por un rato, nadie quiso volver a encontrar la ruta correcta."],alt:"Un recuerdo de viaje soleado creado con NoFi"},
    de:{title:"Irgendwo auf dem Weg zum Meer",text:["Wir bogen falsch ab und fanden eine von der Sonne gewärmte Mauer.","Aus einer Bar in der Nähe kam Musik. Eine Weile wollte niemand den richtigen Weg zurückfinden."],alt:"Eine sonnige Reiseerinnerung, gestaltet mit NoFi"},
  }},
  {id:"002",slug:"eccoli",image:"/memories/screens/eccoli-full.jpeg",audio:"/memories/audio/eccoli.m4a",duration:14,copy:{
    en:{title:"Then the water moved",text:["For half an hour, only blue.","Then one fin. Another. And three small shadows keeping close."],alt:"A memory of dolphins appearing at sea, made in NoFi"},
    it:{title:"Poi l’acqua si è mossa",text:["Per mezz’ora, soltanto azzurro.","Poi una pinna. Un’altra. E tre piccole ombre rimaste vicine."],alt:"Il ricordo di alcuni delfini apparsi in mare, creato con NoFi"},
    fr:{title:"Puis l’eau a bougé",text:["Pendant une demi-heure, rien que du bleu.","Puis une nageoire. Une autre. Et trois petites ombres restées tout près."],alt:"Le souvenir de dauphins apparus en mer, créé dans NoFi"},
    es:{title:"Entonces el agua se movió",text:["Durante media hora, solo azul.","Luego una aleta. Otra. Y tres pequeñas sombras que no se separaban."],alt:"El recuerdo de unos delfines apareciendo en el mar, creado con NoFi"},
    de:{title:"Dann bewegte sich das Wasser",text:["Eine halbe Stunde lang nur Blau.","Dann eine Flosse. Noch eine. Und drei kleine Schatten, die ganz nah blieben."],alt:"Eine Erinnerung an Delfine im Meer, gestaltet mit NoFi"},
  }},
  {id:"003",slug:"altrove",image:"/memories/screens/altrove-full.jpeg",audio:"/memories/audio/altrove.m4a",duration:26,copy:{
    en:{title:"Elsewhere, for a moment",text:["A red giant stood in the dark while a low note filled the room.","Portugal disappeared. We stayed exactly where we were."],alt:"A surreal evening memory made in NoFi"},
    it:{title:"Altrove, per un momento",text:["Un gigante rosso stava nel buio mentre un suono profondo riempiva la stanza.","Il Portogallo è scomparso. Noi siamo rimasti esattamente lì."],alt:"Un ricordo surreale della sera creato con NoFi"},
    fr:{title:"Ailleurs, le temps d’un instant",text:["Un géant rouge se tenait dans l’obscurité tandis qu’une note profonde emplissait la pièce.","Le Portugal a disparu. Nous sommes restés exactement là."],alt:"Un souvenir surréaliste du soir créé dans NoFi"},
    es:{title:"En otra parte, por un momento",text:["Un gigante rojo esperaba en la oscuridad mientras una nota grave llenaba la sala.","Portugal desapareció. Nosotros nos quedamos exactamente allí."],alt:"Un recuerdo nocturno surrealista creado con NoFi"},
    de:{title:"Für einen Moment anderswo",text:["Ein roter Riese stand im Dunkeln, während ein tiefer Ton den Raum füllte.","Portugal verschwand. Wir blieben genau dort."],alt:"Eine surreale Abenderinnerung, gestaltet mit NoFi"},
  }},
];
