import type { Locale } from "@/lib/i18n";

type PageCopy = {
  navigation: string; fragmentsLink: string; privacy: string; languageLabel: string;
  heroTitle: string; heroSubline: string; almostReady: string; platform: string;
  memoryDate: string; memoryTime: string; heroMemory: string; hold: string; kept: string;
  positionTitle: string; positionBody: string; fragmentsEyebrow: string; fragmentsTitle: string;
  voiceLabel: string; voiceQuote: string; voiceNote: string; photoLabel: string; photoDate: string; photoNote: string; photoAlt: string;
  capsuleLabel: string; capsuleOpen: string; capsuleDuration: string;
  privacyTitle: string; privacyBody: string; privacyLine: string; footerLine: string;
  play: string; pause: string; timeline: string;
  metaTitle: string; metaDescription: string; socialDescription: string; socialImageAlt: string;
};

export const comingSoonCopy: Record<Locale, PageCopy> = {
  en: {navigation:"Pre-launch navigation",fragmentsLink:"Fragments",privacy:"Privacy",languageLabel:"Language",heroTitle:"Keep what mattered.",heroSubline:"Photos. Voices. Little things you’d otherwise forget.",almostReady:"NoFi is almost ready.",platform:"Android · 2026",memoryDate:"Tuesday, 18 August",memoryTime:"23:41",heroMemory:"You fell asleep before we reached the sea.",hold:"Hold to remember",kept:"kept.",positionTitle:"Not everything belongs in a feed.",positionBody:"Some things are worth keeping without sharing them.",fragmentsEyebrow:"Three small traces",fragmentsTitle:"A memory is rarely just one thing.",voiceLabel:"Voice · 00:23",voiceQuote:"We missed our turn.",voiceNote:"Nobody wanted the song to end.",photoLabel:"Photograph",photoDate:"12 May 2024",photoNote:"The water moved. Then three small shadows stayed close.",photoAlt:"A quiet memory of dolphins appearing at sea",capsuleLabel:"Capsule",capsuleOpen:"Open in",capsuleDuration:"2 years, 4 months",privacyTitle:"Yours means yours.",privacyBody:"Your fragments stay with you.",privacyLine:"No feed. No audience. No need to perform.",footerLine:"Made to be kept.",play:"Play this memory",pause:"Pause this memory",timeline:"Memory audio timeline",metaTitle:"NoFi Diary — Keep what mattered. Coming soon.",metaDescription:"Photos, voices and little things you’d otherwise forget. NoFi Diary is coming to Android.",socialDescription:"A quiet place for the photographs, voices and moments you want to keep.",socialImageAlt:"A tactile NoFi Diary memory made from a photograph, paper and a voice waveform"},
  it: {navigation:"Navigazione pre-lancio",fragmentsLink:"Frammenti",privacy:"Privacy",languageLabel:"Lingua",heroTitle:"Custodisci ciò che contava.",heroSubline:"Foto. Voci. Piccole cose che altrimenti dimenticheresti.",almostReady:"NoFi è quasi pronto.",platform:"Android · 2026",memoryDate:"Martedì 18 agosto",memoryTime:"23:41",heroMemory:"Ti sei addormentato prima che arrivassimo al mare.",hold:"Tieni premuto per ricordare",kept:"custodito.",positionTitle:"Non tutto appartiene a un feed.",positionBody:"Alcune cose vale la pena custodirle senza condividerle.",fragmentsEyebrow:"Tre piccole tracce",fragmentsTitle:"Un ricordo non è quasi mai una cosa sola.",voiceLabel:"Voce · 00:23",voiceQuote:"Abbiamo mancato la svolta.",voiceNote:"Nessuno voleva che la canzone finisse.",photoLabel:"Fotografia",photoDate:"12 maggio 2024",photoNote:"L’acqua si è mossa. Poi tre piccole ombre sono rimaste vicine.",photoAlt:"Il ricordo quieto di alcuni delfini apparsi in mare",capsuleLabel:"Capsula",capsuleOpen:"Apri tra",capsuleDuration:"2 anni e 4 mesi",privacyTitle:"Tuo significa tuo.",privacyBody:"I tuoi frammenti restano con te.",privacyLine:"Niente feed. Niente pubblico. Nessun bisogno di esibirsi.",footerLine:"Fatto per essere custodito.",play:"Ascolta questo ricordo",pause:"Metti in pausa questo ricordo",timeline:"Posizione nell’audio del ricordo",metaTitle:"NoFi Diary — Custodisci ciò che contava. Prossimamente.",metaDescription:"Foto, voci e piccole cose che altrimenti dimenticheresti. NoFi Diary arriverà su Android.",socialDescription:"Un luogo quieto per le fotografie, le voci e i momenti che vuoi custodire.",socialImageAlt:"Un ricordo tattile di NoFi Diary fatto di fotografia, carta e una forma d’onda vocale"},
  fr: {navigation:"Navigation avant le lancement",fragmentsLink:"Fragments",privacy:"Confidentialité",languageLabel:"Langue",heroTitle:"Gardez ce qui comptait.",heroSubline:"Des photos. Des voix. Ces petites choses que l’on finirait par oublier.",almostReady:"NoFi est presque prêt.",platform:"Android · 2026",memoryDate:"Mardi 18 août",memoryTime:"23:41",heroMemory:"Tu t’es endormi avant que nous arrivions à la mer.",hold:"Maintenez pour vous en souvenir",kept:"gardé.",positionTitle:"Tout n’a pas sa place dans un fil.",positionBody:"Certaines choses méritent d’être gardées sans être partagées.",fragmentsEyebrow:"Trois petites traces",fragmentsTitle:"Un souvenir se résume rarement à une seule chose.",voiceLabel:"Voix · 00:23",voiceQuote:"Nous avons manqué la sortie.",voiceNote:"Personne ne voulait que la chanson se termine.",photoLabel:"Photographie",photoDate:"12 mai 2024",photoNote:"L’eau a bougé. Puis trois petites ombres sont restées tout près.",photoAlt:"Le souvenir paisible de dauphins apparus en mer",capsuleLabel:"Capsule",capsuleOpen:"À ouvrir dans",capsuleDuration:"2 ans et 4 mois",privacyTitle:"À vous, vraiment.",privacyBody:"Vos fragments restent avec vous.",privacyLine:"Pas de fil. Pas de public. Rien à prouver.",footerLine:"Fait pour être gardé.",play:"Écouter ce souvenir",pause:"Mettre ce souvenir en pause",timeline:"Position dans l’enregistrement du souvenir",metaTitle:"NoFi Diary — Gardez ce qui comptait. Bientôt disponible.",metaDescription:"Des photos, des voix et ces petites choses que l’on finirait par oublier. NoFi Diary arrive sur Android.",socialDescription:"Un lieu paisible pour les photographies, les voix et les moments que vous souhaitez garder.",socialImageAlt:"Un souvenir tactile NoFi Diary composé d’une photographie, de papier et d’une onde vocale"},
  es: {navigation:"Navegación previa al lanzamiento",fragmentsLink:"Fragmentos",privacy:"Privacidad",languageLabel:"Idioma",heroTitle:"Guarda lo que importó.",heroSubline:"Fotos. Voces. Pequeñas cosas que, de otro modo, olvidarías.",almostReady:"NoFi está casi listo.",platform:"Android · 2026",memoryDate:"Martes, 18 de agosto",memoryTime:"23:41",heroMemory:"Te dormiste antes de que llegáramos al mar.",hold:"Mantén pulsado para recordar",kept:"guardado.",positionTitle:"No todo tiene que acabar en un feed.",positionBody:"Hay cosas que merece la pena guardar sin compartirlas.",fragmentsEyebrow:"Tres pequeñas huellas",fragmentsTitle:"Un recuerdo casi nunca es una sola cosa.",voiceLabel:"Voz · 00:23",voiceQuote:"Nos pasamos la salida.",voiceNote:"Nadie quería que terminara la canción.",photoLabel:"Fotografía",photoDate:"12 de mayo de 2024",photoNote:"El agua se movió. Después, tres pequeñas sombras permanecieron juntas.",photoAlt:"El recuerdo sereno de unos delfines apareciendo en el mar",capsuleLabel:"Cápsula",capsuleOpen:"Abrir dentro de",capsuleDuration:"2 años y 4 meses",privacyTitle:"Tuyo significa tuyo.",privacyBody:"Tus fragmentos se quedan contigo.",privacyLine:"Sin feed. Sin público. Sin tener que aparentar.",footerLine:"Hecho para conservarse.",play:"Escucha este recuerdo",pause:"Pausa este recuerdo",timeline:"Posición en el audio del recuerdo",metaTitle:"NoFi Diary — Guarda lo que importó. Muy pronto.",metaDescription:"Fotos, voces y pequeñas cosas que, de otro modo, olvidarías. NoFi Diary llegará a Android.",socialDescription:"Un lugar tranquilo para las fotografías, las voces y los momentos que quieres guardar.",socialImageAlt:"Un recuerdo táctil de NoFi Diary hecho de una fotografía, papel y una onda de voz"},
  de: {navigation:"Navigation vor dem Start",fragmentsLink:"Fragmente",privacy:"Datenschutz",languageLabel:"Sprache",heroTitle:"Bewahre, was wichtig war.",heroSubline:"Fotos. Stimmen. Kleine Dinge, die du sonst vergessen würdest.",almostReady:"NoFi ist fast so weit.",platform:"Android · 2026",memoryDate:"Dienstag, 18. August",memoryTime:"23:41",heroMemory:"Du bist eingeschlafen, bevor wir das Meer erreichten.",hold:"Zum Erinnern gedrückt halten",kept:"bewahrt.",positionTitle:"Nicht alles gehört in einen Feed.",positionBody:"Manche Dinge sind es wert, bewahrt zu werden, ohne sie zu teilen.",fragmentsEyebrow:"Drei kleine Spuren",fragmentsTitle:"Eine Erinnerung ist selten nur eine Sache.",voiceLabel:"Stimme · 00:23",voiceQuote:"Wir haben die Abzweigung verpasst.",voiceNote:"Niemand wollte, dass das Lied endet.",photoLabel:"Fotografie",photoDate:"12. Mai 2024",photoNote:"Das Wasser bewegte sich. Dann blieben drei kleine Schatten dicht beieinander.",photoAlt:"Eine stille Erinnerung an Delfine, die im Meer auftauchen",capsuleLabel:"Zeitkapsel",capsuleOpen:"Öffnen in",capsuleDuration:"2 Jahren, 4 Monaten",privacyTitle:"Deins heißt deins.",privacyBody:"Deine Fragmente bleiben bei dir.",privacyLine:"Kein Feed. Kein Publikum. Nichts vorzuführen.",footerLine:"Gemacht, um bewahrt zu werden.",play:"Diese Erinnerung anhören",pause:"Diese Erinnerung pausieren",timeline:"Position in der Audioaufnahme der Erinnerung",metaTitle:"NoFi Diary — Bewahre, was wichtig war. Demnächst verfügbar.",metaDescription:"Fotos, Stimmen und kleine Dinge, die du sonst vergessen würdest. NoFi Diary erscheint für Android.",socialDescription:"Ein stiller Ort für Fotos, Stimmen und Momente, die du bewahren möchtest.",socialImageAlt:"Eine haptische NoFi-Diary-Erinnerung aus einem Foto, Papier und einer Sprachwellenform"}
};
