import type { Locale } from "@/lib/i18n";

type PageCopy = {
  navigation: string; fragmentsLink: string; privacy: string; languageLabel: string;
  heroTitle: string; heroSubline: string; almostReady: string; platform: string;
  memoryDate: string; memoryTime: string; heroMemory: string; hold: string; kept: string;
  positionTitle: string; positionBody: string; fragmentsEyebrow: string; fragmentsTitle: string;
  voiceLabel: string; voiceQuote: string; voiceNote: string; photoLabel: string; photoDate: string; photoNote: string; photoAlt: string;
  capsuleLabel: string; capsuleOpen: string; capsuleDuration: string;
  privacyTitle: string; privacyBody: string; privacyLine: string; footerLine: string;
  play: string; pause: string; timeline: string;
  metaTitle: string; metaDescription: string; socialDescription: string; socialImageAlt: string;
};

export const comingSoonCopy: Record<Locale, PageCopy> = {
  en: {navigation:"Pre-launch navigation",fragmentsLink:"Fragments",privacy:"Privacy",languageLabel:"Language",heroTitle:"Keep what mattered.",heroSubline:"Photos. Voices. Little things you’d otherwise forget.",almostReady:"NoFi is almost ready.",platform:"Android · 2026",memoryDate:"Tuesday, 18 August",memoryTime:"23:41",heroMemory:"You fell asleep before we reached the sea.",hold:"Hold to remember",kept:"kept.",positionTitle:"Not everything belongs in a feed.",positionBody:"Some things are worth keeping without sharing them.",fragmentsEyebrow:"Three small traces",fragmentsTitle:"A memory is rarely just one thing.",voiceLabel:"Voice · 00:23",voiceQuote:"We missed our turn.",voiceNote:"Nobody wanted the song to end.",photoLabel:"Photograph",photoDate:"12 May 2024",photoNote:"The water moved. Then three small shadows stayed close.",photoAlt:"Dolphins surfacing in a calm sea",capsuleLabel:"Capsule",capsuleOpen:"Open in",capsuleDuration:"2 years, 4 months",privacyTitle:"Yours means yours.",privacyBody:"Your fragments stay with you.",privacyLine:"No feed. No audience. No need to perform.",footerLine:"Made to be kept.",play:"Play this memory",pause:"Pause this memory",timeline:"Memory audio timeline",metaTitle:"NoFi Diary — Keep what mattered. Coming soon.",metaDescription:"Photos, voices and little things you’d otherwise forget. NoFi Diary is coming to Android.",socialDescription:"A quiet place for the photographs, voices and moments you want to keep.",socialImageAlt:"A tactile NoFi Diary memory made from a photograph, paper and a voice waveform"},
  it: {navigation:"Navigazione pre-lancio",fragmentsLink:"Frammenti",privacy:"Privacy",languageLabel:"Lingua",heroTitle:"Custodisci ciò che conta.",heroSubline:"Foto. Voci. Piccole cose che altrimenti dimenticheresti.",almostReady:"NoFi è quasi pronto.",platform:"Android · 2026",memoryDate:"Martedì 18 agosto",memoryTime:"23:41",heroMemory:"Ti sei addormentato prima che arrivassimo al mare.",hold:"Tieni premuto per ricordare",kept:"custodito.",positionTitle:"Non tutto deve finire in un feed.",positionBody:"Ci sono cose che vale la pena custodire senza condividerle.",fragmentsEyebrow:"Tre piccole tracce",fragmentsTitle:"Un ricordo non è quasi mai una cosa sola.",voiceLabel:"Voce · 00:23",voiceQuote:"Abbiamo sbagliato strada.",voiceNote:"Nessuno voleva che la canzone finisse.",photoLabel:"Fotografia",photoDate:"12 maggio 2024",photoNote:"L’acqua si è mossa. Poi tre piccole ombre sono rimaste vicine.",photoAlt:"Tre delfini affiorano in un mare calmo",capsuleLabel:"Capsula",capsuleOpen:"Si aprirà tra",capsuleDuration:"2 anni e 4 mesi",privacyTitle:"Ciò che è tuo resta tuo.",privacyBody:"I tuoi frammenti restano con te.",privacyLine:"Niente feed. Niente pubblico. Niente da dimostrare.",footerLine:"Fatto per essere custodito.",play:"Ascolta questo ricordo",pause:"Metti in pausa questo ricordo",timeline:"Avanzamento dell’audio del ricordo",metaTitle:"NoFi Diary — Custodisci ciò che conta. Prossimamente.",metaDescription:"Foto, voci e piccole cose che altrimenti dimenticheresti. NoFi Diary arriverà su Android.",socialDescription:"Un luogo intimo per le fotografie, le voci e i momenti che vuoi custodire.",socialImageAlt:"Un ricordo NoFi Diary composto da una fotografia, carta e una forma d’onda vocale"},
  fr: {navigation:"Navigation avant le lancement",fragmentsLink:"Fragments",privacy:"Confidentialité",languageLabel:"Langue",heroTitle:"Gardez ce qui compte.",heroSubline:"Des photos. Des voix. Ces petites choses que l’on finirait par oublier.",almostReady:"NoFi est presque prêt.",platform:"Android · 2026",memoryDate:"Mardi 18 août",memoryTime:"23:41",heroMemory:"Vous dormiez déjà avant notre arrivée à la mer.",hold:"Maintenez pour vous en souvenir",kept:"conservé.",positionTitle:"Tout n’a pas sa place dans un fil d’actualité.",positionBody:"Certaines choses méritent d’être gardées sans être partagées.",fragmentsEyebrow:"Trois petites traces",fragmentsTitle:"Un souvenir tient rarement en une seule chose.",voiceLabel:"Voix · 00:23",voiceQuote:"On a raté la sortie.",voiceNote:"Personne ne voulait que la chanson s’arrête.",photoLabel:"Photographie",photoDate:"12 mai 2024",photoNote:"L’eau a frémi. Puis trois petites ombres sont restées tout près.",photoAlt:"Trois dauphins remontent à la surface d’une mer calme",capsuleLabel:"Capsule",capsuleOpen:"S’ouvrira dans",capsuleDuration:"2 ans et 4 mois",privacyTitle:"Ce qui est à vous reste à vous.",privacyBody:"Vos fragments restent avec vous.",privacyLine:"Pas de fil. Pas de public. Rien à prouver.",footerLine:"Fait pour être gardé.",play:"Écouter ce souvenir",pause:"Mettre ce souvenir en pause",timeline:"Progression de l’enregistrement du souvenir",metaTitle:"NoFi Diary — Gardez ce qui compte. Bientôt disponible.",metaDescription:"Des photos, des voix et ces petites choses que l’on finirait par oublier. NoFi Diary arrive bientôt sur Android.",socialDescription:"Un lieu intime pour les photos, les voix et les moments que vous souhaitez garder.",socialImageAlt:"Un souvenir NoFi Diary composé d’une photographie, de papier et d’une onde vocale"},
  es: {navigation:"Navegación previa al lanzamiento",fragmentsLink:"Fragmentos",privacy:"Privacidad",languageLabel:"Idioma",heroTitle:"Guarda lo que importa.",heroSubline:"Fotos. Voces. Pequeñas cosas que, de otro modo, olvidarías.",almostReady:"NoFi está casi listo.",platform:"Android · 2026",memoryDate:"Martes, 18 de agosto",memoryTime:"23:41",heroMemory:"Te dormiste antes de que llegáramos al mar.",hold:"Mantén pulsado para recordar",kept:"guardado.",positionTitle:"No todo tiene que acabar en un feed.",positionBody:"Hay cosas que merece la pena guardar sin compartirlas.",fragmentsEyebrow:"Tres pequeñas huellas",fragmentsTitle:"Un recuerdo casi nunca es una sola cosa.",voiceLabel:"Voz · 00:23",voiceQuote:"Nos pasamos la salida.",voiceNote:"Nadie quería que se acabara la canción.",photoLabel:"Fotografía",photoDate:"12 de mayo de 2024",photoNote:"El agua se agitó. Después, tres pequeñas sombras siguieron juntas.",photoAlt:"Tres delfines asoman en un mar en calma",capsuleLabel:"Cápsula",capsuleOpen:"Se abrirá dentro de",capsuleDuration:"2 años y 4 meses",privacyTitle:"Lo tuyo sigue siendo tuyo.",privacyBody:"Tus fragmentos se quedan contigo.",privacyLine:"Sin feed. Sin público. Nada que demostrar.",footerLine:"Hecho para conservarse.",play:"Escucha este recuerdo",pause:"Pausa este recuerdo",timeline:"Progreso del audio del recuerdo",metaTitle:"NoFi Diary — Guarda lo que importa. Muy pronto.",metaDescription:"Fotos, voces y pequeñas cosas que, de otro modo, olvidarías. NoFi Diary llegará a Android.",socialDescription:"Un lugar íntimo para las fotos, las voces y los momentos que quieres guardar.",socialImageAlt:"Un recuerdo de NoFi Diary compuesto por una fotografía, papel y una onda de voz"},
  de: {navigation:"Navigation vor dem Start",fragmentsLink:"Fragmente",privacy:"Datenschutz",languageLabel:"Sprache",heroTitle:"Bewahre, was zählt.",heroSubline:"Fotos. Stimmen. Kleine Dinge, die du sonst vergessen würdest.",almostReady:"NoFi ist fast so weit.",platform:"Android · 2026",memoryDate:"Dienstag, 18. August",memoryTime:"23:41",heroMemory:"Du bist eingeschlafen, bevor wir am Meer waren.",hold:"Zum Erinnern gedrückt halten",kept:"aufbewahrt.",positionTitle:"Nicht alles gehört in einen Feed.",positionBody:"Manche Dinge sind es wert, bewahrt zu werden, ohne sie zu teilen.",fragmentsEyebrow:"Drei kleine Spuren",fragmentsTitle:"Eine Erinnerung besteht selten aus nur einer Sache.",voiceLabel:"Sprachnotiz · 00:23",voiceQuote:"Wir haben die Abfahrt verpasst.",voiceNote:"Niemand wollte, dass das Lied zu Ende geht.",photoLabel:"Fotografie",photoDate:"12. Mai 2024",photoNote:"Das Wasser regte sich. Dann blieben drei kleine Schatten dicht beieinander.",photoAlt:"Drei Delfine tauchen in einem ruhigen Meer auf",capsuleLabel:"Zeitkapsel",capsuleOpen:"Öffnet in",capsuleDuration:"2 Jahren und 4 Monaten",privacyTitle:"Was deins ist, bleibt deins.",privacyBody:"Deine Fragmente bleiben bei dir.",privacyLine:"Kein Feed. Kein Publikum. Nichts zu beweisen.",footerLine:"Gemacht, um bewahrt zu werden.",play:"Diese Erinnerung anhören",pause:"Diese Erinnerung pausieren",timeline:"Fortschritt der Audioaufnahme",metaTitle:"NoFi Diary — Bewahre, was zählt. Demnächst verfügbar.",metaDescription:"Fotos, Stimmen und kleine Dinge, die du sonst vergessen würdest. NoFi Diary erscheint demnächst für Android.",socialDescription:"Ein persönlicher Ort für Fotos, Stimmen und Momente, die du bewahren möchtest.",socialImageAlt:"Eine NoFi-Diary-Erinnerung aus einem Foto, Papier und einer Sprachwellenform"}
};
