import type { Locale } from "@/lib/i18n";

export type FragmentStatus = "draft" | "published";
export type FragmentCopy = { title: string; excerpt: string; body: string; imageAlt: string; socialTitle: string; socialDescription: string };
export type NofiFragment = {
  id: string;
  slug: string;
  status: FragmentStatus;
  order: number;
  publishAt: string;
  image: string;
  audio?: string;
  copy: Record<Locale, FragmentCopy>;
};

export const fragments: readonly NofiFragment[] = [
  { id:"001",slug:"001-road-to-sea",status:"published",order:1,publishAt:"2026-09-02",image:"/images/coming-soon/fragment-001-road-to-sea.webp",copy:{
    en:{title:"Before we reached the sea",excerpt:"A road, a sleeping passenger, and something worth keeping.",body:"You fell asleep before we reached the sea. I kept driving with the windows barely open and the last light following us around every bend.",imageAlt:"A printed photograph of a quiet coastal road arranged on handmade paper",socialTitle:"Fragment 001 — Before we reached the sea",socialDescription:"One of the first fragments from NoFi Diary: a private, offline place for the moments you want to keep."},
    it:{title:"Prima di arrivare al mare",excerpt:"Una strada, qualcuno che dorme e qualcosa da custodire.",body:"Ti sei addormentato prima che arrivassimo al mare. Ho continuato a guidare con i finestrini appena aperti e l’ultima luce che ci seguiva dietro ogni curva.",imageAlt:"Una fotografia stampata di una tranquilla strada costiera appoggiata su carta artigianale",socialTitle:"Frammento 001 — Prima di arrivare al mare",socialDescription:"Uno dei primi frammenti di NoFi Diary: un luogo privato e offline per i momenti che vuoi custodire."},
    fr:{title:"Avant d’arriver à la mer",excerpt:"Une route, quelqu’un qui dort et quelque chose à garder.",body:"Vous dormiez déjà avant notre arrivée à la mer. J’ai continué à conduire, les vitres entrouvertes, tandis que les dernières lueurs nous suivaient à chaque virage.",imageAlt:"Une photographie imprimée d’une route côtière paisible posée sur du papier artisanal",socialTitle:"Fragment 001 — Avant d’arriver à la mer",socialDescription:"L’un des premiers fragments de NoFi Diary : un lieu privé et hors ligne pour les moments que vous souhaitez garder."},
    es:{title:"Antes de llegar al mar",excerpt:"Una carretera, alguien dormido y algo que guardar.",body:"Te dormiste antes de que llegáramos al mar. Seguí conduciendo con las ventanillas entreabiertas y la última luz siguiéndonos en cada curva.",imageAlt:"Una fotografía impresa de una tranquila carretera costera sobre papel artesanal",socialTitle:"Fragmento 001 — Antes de llegar al mar",socialDescription:"Uno de los primeros fragmentos de NoFi Diary: un lugar privado y sin conexión para los momentos que quieres guardar."},
    de:{title:"Bevor wir am Meer waren",excerpt:"Eine Straße, ein schlafender Mensch und etwas, das bleiben darf.",body:"Du bist eingeschlafen, bevor wir am Meer waren. Ich fuhr weiter, die Fenster einen Spalt offen, während uns das letzte Licht durch jede Kurve folgte.",imageAlt:"Ein gedrucktes Foto einer ruhigen Küstenstraße auf handgeschöpftem Papier",socialTitle:"Fragment 001 — Bevor wir am Meer waren",socialDescription:"Eines der ersten Fragmente aus NoFi Diary: ein privater Offline-Ort für die Momente, die du bewahren möchtest."}
  }},
  { id:"002",slug:"002-the-song-kept-playing",status:"draft",order:2,publishAt:"2026-09-10",image:"/images/coming-soon/fragment-003-elsewhere.webp",audio:"/memories/audio/fuori-strada.m4a",copy:{
    en:{title:"The song kept playing",excerpt:"We missed the turn on purpose.",body:"The road grew longer, the chorus came back, and nobody reached for the map.",imageAlt:"A hazy road memory assembled from paper and a photograph",socialTitle:"Fragment 002 — The song kept playing",socialDescription:"A small voice fragment from NoFi Diary."},
    it:{title:"La canzone continuava",excerpt:"Abbiamo mancato la svolta apposta.",body:"La strada si è allungata, è tornato il ritornello e nessuno ha cercato la mappa.",imageAlt:"Il ricordo sfumato di una strada composto con carta e una fotografia",socialTitle:"Frammento 002 — La canzone continuava",socialDescription:"Un piccolo frammento sonoro di NoFi Diary."},
    fr:{title:"La chanson continuait",excerpt:"On a raté la sortie exprès.",body:"La route s’est allongée, le refrain est revenu et personne n’a cherché la carte.",imageAlt:"Le souvenir brumeux d’une route composé de papier et d’une photographie",socialTitle:"Fragment 002 — La chanson continuait",socialDescription:"Un petit fragment sonore de NoFi Diary."},
    es:{title:"La canción seguía sonando",excerpt:"Nos saltamos la salida a propósito.",body:"La carretera se alargó, volvió el estribillo y nadie buscó el mapa.",imageAlt:"El recuerdo difuso de una carretera compuesto con papel y una fotografía",socialTitle:"Fragmento 002 — La canción seguía sonando",socialDescription:"Un pequeño fragmento sonoro de NoFi Diary."},
    de:{title:"Das Lied lief weiter",excerpt:"Wir verpassten die Abfahrt mit Absicht.",body:"Die Straße wurde länger, der Refrain kam zurück und niemand griff nach der Karte.",imageAlt:"Eine verschwommene Straßenerinnerung aus Papier und einem Foto",socialTitle:"Fragment 002 — Das Lied lief weiter",socialDescription:"Ein kleines Klangfragment aus NoFi Diary."}
  }},
  { id:"003",slug:"003-three-small-shadows",status:"draft",order:3,publishAt:"2026-09-20",image:"/images/coming-soon/dolphins-instant-v2.webp",copy:{
    en:{title:"Three small shadows",excerpt:"The water moved first.",body:"For a second the sea looked empty. Then three small shadows stayed close enough to become a memory.",imageAlt:"Three dolphins surfacing in a calm sea",socialTitle:"Fragment 003 — Three small shadows",socialDescription:"A photographic fragment from NoFi Diary."},
    it:{title:"Tre piccole ombre",excerpt:"Prima si è mossa l’acqua.",body:"Per un istante il mare sembrava vuoto. Poi tre piccole ombre sono rimaste abbastanza vicine da diventare un ricordo.",imageAlt:"Tre delfini affiorano in un mare calmo",socialTitle:"Frammento 003 — Tre piccole ombre",socialDescription:"Un frammento fotografico di NoFi Diary."},
    fr:{title:"Trois petites ombres",excerpt:"L’eau a frémi la première.",body:"Un instant, la mer a paru vide. Puis trois petites ombres sont restées assez près pour devenir un souvenir.",imageAlt:"Trois dauphins remontent à la surface d’une mer calme",socialTitle:"Fragment 003 — Trois petites ombres",socialDescription:"Un fragment photographique de NoFi Diary."},
    es:{title:"Tres pequeñas sombras",excerpt:"El agua se movió primero.",body:"Por un instante, el mar parecía vacío. Después, tres pequeñas sombras siguieron lo bastante cerca como para convertirse en un recuerdo.",imageAlt:"Tres delfines asoman en un mar en calma",socialTitle:"Fragmento 003 — Tres pequeñas sombras",socialDescription:"Un fragmento fotográfico de NoFi Diary."},
    de:{title:"Drei kleine Schatten",excerpt:"Zuerst regte sich das Wasser.",body:"Einen Augenblick lang wirkte das Meer leer. Dann blieben drei kleine Schatten nah genug, um zu einer Erinnerung zu werden.",imageAlt:"Drei Delfine tauchen in einem ruhigen Meer auf",socialTitle:"Fragment 003 — Drei kleine Schatten",socialDescription:"Ein fotografisches Fragment aus NoFi Diary."}
  }},
  { id:"004",slug:"004-some-memories-have-a-sound",status:"draft",order:4,publishAt:"2026-10-02",image:"/images/coming-soon/hero-memory.webp",copy:{
    en:{title:"Some memories have a sound",excerpt:"Not a soundtrack. The moment itself.",body:"A breath before speaking. A cup set down on the table. The part of a voice a photograph could never hold.",imageAlt:"A layered paper memory with a small voice waveform",socialTitle:"Fragment 004 — Some memories have a sound",socialDescription:"A note about voices, photographs and private memory from NoFi Diary."},
    it:{title:"Alcuni ricordi hanno un suono",excerpt:"Non una colonna sonora. Il momento stesso.",body:"Un respiro prima di parlare. Una tazza appoggiata sul tavolo. Quella parte di una voce che una fotografia non potrebbe mai trattenere.",imageAlt:"Un ricordo composto da strati di carta e una piccola forma d’onda vocale",socialTitle:"Frammento 004 — Alcuni ricordi hanno un suono",socialDescription:"Una nota su voci, fotografie e ricordi privati di NoFi Diary."},
    fr:{title:"Certains souvenirs ont un son",excerpt:"Pas une bande-son. Le moment lui-même.",body:"Un souffle avant de parler. Une tasse posée sur la table. Cette part d’une voix qu’aucune photographie ne pourrait retenir.",imageAlt:"Un souvenir composé de papiers superposés et d’une petite onde vocale",socialTitle:"Fragment 004 — Certains souvenirs ont un son",socialDescription:"Une note de NoFi Diary sur les voix, les photographies et les souvenirs privés."},
    es:{title:"Algunos recuerdos tienen sonido",excerpt:"No una banda sonora. El momento en sí.",body:"Una respiración antes de hablar. Una taza apoyada en la mesa. Esa parte de una voz que ninguna fotografía podría guardar.",imageAlt:"Un recuerdo hecho de capas de papel y una pequeña onda de voz",socialTitle:"Fragmento 004 — Algunos recuerdos tienen sonido",socialDescription:"Una nota de NoFi Diary sobre voces, fotografías y recuerdos privados."},
    de:{title:"Manche Erinnerungen haben einen Klang",excerpt:"Kein Soundtrack. Der Moment selbst.",body:"Ein Atemzug vor dem Sprechen. Eine Tasse, die auf den Tisch gestellt wird. Der Teil einer Stimme, den kein Foto festhalten könnte.",imageAlt:"Eine Erinnerung aus geschichtetem Papier und einer kleinen Sprachwellenform",socialTitle:"Fragment 004 — Manche Erinnerungen haben einen Klang",socialDescription:"Eine Notiz von NoFi Diary über Stimmen, Fotos und private Erinnerungen."}
  }}
] as const;

export const publishedFragments = fragments.filter(fragment => fragment.status === "published");
export const findPublishedFragment = (slug: string) => publishedFragments.find(fragment => fragment.slug === slug);
