"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { Locale, localePath } from "@/lib/i18n";

type JourneyStep = { title:string; body:string; note:string; image:string; alt:string; link?:string; linkLabel?:string };
type JourneyCopy = { kicker:string; title:string; intro:string; previous:string; next:string; count:string; closing:string; privacyLink:string; steps:JourneyStep[] };

const journeyCopy: Record<Locale,JourneyCopy> = {
  en:{kicker:"One moment, four quiet gestures",title:"How a memory comes together.",intro:"A memory in NoFi is not a file you upload. It is something you compose—one piece at a time.",previous:"Previous step",next:"Next step",count:"of",closing:"Keep it private. Revisit it later. Export it. Or pass it to someone when it feels right.",privacyLink:"See how your memories stay yours",steps:[
    {title:"Compose the moment",body:"Add a photo, choose the atmosphere and decide which pieces belong in the memory.",note:"The Memory Canvas brings photo, voice, stickers and visual details into one private page.",image:"/images/app/journey-compose.jpeg",alt:"A photograph being composed in the NoFi Memory Canvas"},
    {title:"Leave a voice trace",body:"Record a few words, a laugh, the sound of a place or something you do not want to write down.",note:"Voice stays inside the memory and can be replayed when you return to it.",image:"/images/app/journey-voice.jpeg",alt:"NoFi recording a voice trace inside a memory"},
    {title:"Make the page yours",body:"Add tape, botanical details or a visual sign that recalls how the moment felt.",note:"Every element can be selected, moved or removed before the page is saved.",image:"/images/app/journey-stickers.jpeg",alt:"A memory being decorated with stickers in NoFi",link:"/stickers",linkLabel:"Explore Sticker Packs"},
    {title:"Keep it—or pass it on",body:"Your memory remains yours. When you choose, pass it directly to someone nearby or use another app.",note:"Nothing becomes public. NoFi has no feed and no audience waiting for your memories.",image:"/images/app/journey-share.jpeg",alt:"The optional Pass a memory screen in NoFi",link:"/#privacy",linkLabel:"Privacy & ownership"}
  ]},
  it:{kicker:"Un momento, quattro gesti silenziosi",title:"Come prende forma un ricordo.",intro:"Un ricordo in NoFi non è un file da caricare. È qualcosa che componi, un frammento alla volta.",previous:"Passaggio precedente",next:"Passaggio successivo",count:"di",closing:"Tienilo privato. Ritrovalo più avanti. Esportalo. Oppure passalo a qualcuno quando ti sembra il momento giusto.",privacyLink:"Scopri perché i tuoi ricordi restano tuoi",steps:[
    {title:"Componi il momento",body:"Aggiungi una foto, scegli l’atmosfera e decidi quali frammenti appartengono al ricordo.",note:"La Tela del ricordo riunisce foto, voce, sticker e dettagli visuali in una pagina privata.",image:"/images/app/journey-compose.jpeg",alt:"Una fotografia composta nella Tela del ricordo di NoFi"},
    {title:"Lascia una traccia vocale",body:"Registra poche parole, una risata, il suono di un luogo o qualcosa che non vuoi scrivere.",note:"La voce resta nel ricordo e può essere riascoltata quando torni a visitarlo.",image:"/images/app/journey-voice.jpeg",alt:"NoFi registra una traccia vocale dentro un ricordo"},
    {title:"Rendi tua la pagina",body:"Aggiungi tape, dettagli botanici o un segno che ricordi come ti faceva sentire quel momento.",note:"Ogni elemento può essere selezionato, spostato o rimosso prima di salvare la pagina.",image:"/images/app/journey-stickers.jpeg",alt:"Un ricordo decorato con gli sticker in NoFi",link:"/stickers",linkLabel:"Esplora gli Sticker Pack"},
    {title:"Custodiscilo o passalo",body:"Il ricordo resta tuo. Quando vuoi, puoi passarlo a qualcuno vicino o usare un’altra app.",note:"Nulla diventa pubblico. NoFi non ha un feed né un pubblico in attesa dei tuoi ricordi.",image:"/images/app/journey-share.jpeg",alt:"La schermata facoltativa Passa un ricordo di NoFi",link:"/#privacy",linkLabel:"Privacy e proprietà"}
  ]},
  fr:{kicker:"Un moment, quatre gestes discrets",title:"Comment un souvenir prend forme.",intro:"Dans NoFi, un souvenir n’est pas un fichier à téléverser. Il se compose, fragment après fragment.",previous:"Étape précédente",next:"Étape suivante",count:"sur",closing:"Gardez-le privé. Retrouvez-le plus tard. Exportez-le. Ou transmettez-le lorsque le moment semble juste.",privacyLink:"Voir pourquoi vos souvenirs restent les vôtres",steps:[
    {title:"Composez le moment",body:"Ajoutez une photo, choisissez l’atmosphère et décidez quels fragments appartiennent au souvenir.",note:"La toile réunit photo, voix, stickers et détails visuels dans une page privée.",image:"/images/app/journey-compose.jpeg",alt:"Une photographie composée dans la toile de souvenir NoFi"},
    {title:"Laissez une trace vocale",body:"Enregistrez quelques mots, un rire, le son d’un lieu ou ce que vous ne voulez pas écrire.",note:"La voix reste dans le souvenir et peut être réécoutée lorsque vous y revenez.",image:"/images/app/journey-voice.jpeg",alt:"NoFi enregistre une trace vocale dans un souvenir"},
    {title:"Faites vôtre la page",body:"Ajoutez du ruban, des détails botaniques ou un signe qui rappelle l’émotion du moment.",note:"Chaque élément peut être sélectionné, déplacé ou supprimé avant l’enregistrement.",image:"/images/app/journey-stickers.jpeg",alt:"Un souvenir décoré avec des stickers dans NoFi",link:"/stickers",linkLabel:"Explorer les stickers"},
    {title:"Gardez-le ou transmettez-le",body:"Le souvenir reste à vous. Si vous le décidez, transmettez-le à une personne proche ou via une autre app.",note:"Rien ne devient public. NoFi n’a ni fil public ni audience en attente.",image:"/images/app/journey-share.jpeg",alt:"L’écran facultatif de transmission d’un souvenir NoFi",link:"/#privacy",linkLabel:"Confidentialité et propriété"}
  ]},
  es:{kicker:"Un momento, cuatro gestos tranquilos",title:"Cómo toma forma un recuerdo.",intro:"En NoFi, un recuerdo no es un archivo que subes. Es algo que compones, fragmento a fragmento.",previous:"Paso anterior",next:"Paso siguiente",count:"de",closing:"Mantenlo privado. Vuelve más tarde. Expórtalo. O pásaselo a alguien cuando sea el momento adecuado.",privacyLink:"Descubre por qué tus recuerdos siguen siendo tuyos",steps:[
    {title:"Compón el momento",body:"Añade una foto, elige la atmósfera y decide qué fragmentos pertenecen al recuerdo.",note:"El lienzo reúne foto, voz, stickers y detalles visuales en una página privada.",image:"/images/app/journey-compose.jpeg",alt:"Una fotografía compuesta en el lienzo de recuerdos de NoFi"},
    {title:"Deja una huella de voz",body:"Graba unas palabras, una risa, el sonido de un lugar o algo que no quieras escribir.",note:"La voz permanece dentro del recuerdo para escucharla cuando vuelvas.",image:"/images/app/journey-voice.jpeg",alt:"NoFi graba una huella de voz dentro de un recuerdo"},
    {title:"Haz tuya la página",body:"Añade cinta, detalles botánicos o una señal que recuerde cómo se sentía aquel momento.",note:"Cada elemento puede seleccionarse, moverse o eliminarse antes de guardar.",image:"/images/app/journey-stickers.jpeg",alt:"Un recuerdo decorado con stickers en NoFi",link:"/stickers",linkLabel:"Explorar Sticker Packs"},
    {title:"Guárdalo o pásalo",body:"El recuerdo sigue siendo tuyo. Cuando quieras, pásalo a alguien cercano o usa otra aplicación.",note:"Nada se hace público. NoFi no tiene feed ni una audiencia esperando tus recuerdos.",image:"/images/app/journey-share.jpeg",alt:"La pantalla opcional para pasar un recuerdo en NoFi",link:"/#privacy",linkLabel:"Privacidad y propiedad"}
  ]},
  de:{kicker:"Ein Moment, vier ruhige Gesten",title:"Wie eine Erinnerung entsteht.",intro:"Eine Erinnerung in NoFi ist keine Datei zum Hochladen. Du setzt sie Stück für Stück zusammen.",previous:"Vorheriger Schritt",next:"Nächster Schritt",count:"von",closing:"Bewahre sie privat. Kehre später zurück. Exportiere sie. Oder gib sie weiter, wenn es sich richtig anfühlt.",privacyLink:"Warum deine Erinnerungen dir gehören",steps:[
    {title:"Setze den Moment zusammen",body:"Füge ein Foto hinzu, wähle die Atmosphäre und entscheide, welche Fragmente dazugehören.",note:"Die Erinnerungsfläche verbindet Foto, Stimme, Sticker und visuelle Details auf einer privaten Seite.",image:"/images/app/journey-compose.jpeg",alt:"Ein Foto auf der NoFi-Erinnerungsfläche"},
    {title:"Hinterlasse eine Sprachspur",body:"Nimm ein paar Worte, ein Lachen, den Klang eines Ortes oder etwas auf, das du nicht schreiben möchtest.",note:"Die Stimme bleibt in der Erinnerung und kann beim Wiedersehen abgespielt werden.",image:"/images/app/journey-voice.jpeg",alt:"NoFi nimmt eine Sprachspur in einer Erinnerung auf"},
    {title:"Mach die Seite zu deiner",body:"Füge Klebeband, botanische Details oder ein Zeichen für das Gefühl des Moments hinzu.",note:"Jedes Element lässt sich vor dem Speichern auswählen, verschieben oder entfernen.",image:"/images/app/journey-stickers.jpeg",alt:"Eine Erinnerung wird in NoFi mit Stickern gestaltet",link:"/stickers",linkLabel:"Sticker-Pakete entdecken"},
    {title:"Bewahre sie oder gib sie weiter",body:"Die Erinnerung bleibt deine. Wenn du möchtest, gib sie direkt an jemanden in der Nähe oder über eine andere App weiter.",note:"Nichts wird öffentlich. NoFi hat keinen Feed und kein wartendes Publikum.",image:"/images/app/journey-share.jpeg",alt:"Der optionale NoFi-Bildschirm zum Weitergeben einer Erinnerung",link:"/#privacy",linkLabel:"Privatsphäre und Eigentum"}
  ]}
};

export function MemoryJourney({locale}:{locale:Locale}) {
  const copy=journeyCopy[locale]; const [active,setActive]=useState(0); const step=copy.steps[active];
  const destination=(value:string)=>value.startsWith("/#") ? `${localePath(locale)}${value.slice(1)}` : localePath(locale,value);
  return <section id="how" className="memoryJourney section"><div className="shell">
    <div className="memoryJourneyHeading"><p className="kicker">{copy.kicker}</p><h2>{copy.title}</h2><p>{copy.intro}</p></div>
    <div className="memoryJourneyDesktop"><div className="journeyRail" role="tablist" aria-label={copy.title}>{copy.steps.map((item,index)=><button key={item.title} type="button" role="tab" aria-selected={active===index} aria-controls="journey-panel" onClick={()=>setActive(index)}><span>0{index+1}</span><b>{item.title}</b></button>)}</div><div id="journey-panel" className="journeyPanel" role="tabpanel"><div className="journeyPhone"><Image src={step.image} alt={step.alt} fill priority={active===0} sizes="(max-width:900px) 82vw, 29vw"/></div><div className="journeyCopy"><p className="journeyCount">0{active+1} {copy.count} 04</p><h3>{step.title}</h3><p>{step.body}</p><p className="journeyNote">{step.note}</p>{step.link&&<Link className="textLink" href={destination(step.link)}>{step.linkLabel} →</Link>}<div className="journeyControls"><button type="button" aria-label={copy.previous} disabled={active===0} onClick={()=>setActive(value=>Math.max(0,value-1))}>←</button><button type="button" aria-label={copy.next} disabled={active===3} onClick={()=>setActive(value=>Math.min(3,value+1))}>→</button></div></div></div></div>
    <div className="memoryJourneyMobile">{copy.steps.map((item,index)=><article key={item.title}><p className="journeyCount">0{index+1} {copy.count} 04</p><h3>{item.title}</h3><p>{item.body}</p><div className="journeyPhone"><Image src={item.image} alt={item.alt} fill sizes="88vw"/></div><p className="journeyNote">{item.note}</p>{item.link&&<Link className="textLink" href={destination(item.link)}>{item.linkLabel} →</Link>}</article>)}</div>
    <div className="journeyClosing"><p>{copy.closing}</p><Link className="textLink" href={`${localePath(locale)}#privacy`}>{copy.privacyLink} →</Link></div>
  </div></section>;
}
